{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Adopted from https://gitlab.qdatalabs.com/quantiphi-sagemaker-marketplace-examples/bar-qr-code-detection/blob/master/BarcodeQRcodeScannerNB-ARN.ipynb\n",
    "## Imports"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sagemaker as sage\n",
    "import os\n",
    "import boto3\n",
    "from sagemaker import get_execution_role\n",
    "from sagemaker import transformer\n",
    "from sagemaker import model\n",
    "\n",
    "role = get_execution_role()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Create the session\n",
    "\n",
    "The session remembers our connection parameters to Amazon SageMaker. We'll use it to perform all of our SageMaker operations."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "635521884144\n",
      "us-east-1\n"
     ]
    }
   ],
   "source": [
    "sess = sage.Session()\n",
    "\n",
    "account = sess.boto_session.client('sts').get_caller_identity()['Account']\n",
    "region = sess.boto_session.region_name\n",
    "print(account)\n",
    "print(region)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Create Model\n",
    "\n",
    "Now we use the Bar/QR-code Scanner Model Package to create a model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "from src.model_package_arns import ModelPackageArnProvider"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "arn:aws:sagemaker:us-east-1:865070037744:model-package/bar-qr-code-reader-1571413449-a35a47dda86b16474ecd69ff9f20b46f\n"
     ]
    }
   ],
   "source": [
    "from sagemaker import ModelPackage\n",
    "modelpackage_arn = ModelPackageArnProvider.get_model_package_arn(sess.boto_region_name)\n",
    "\n",
    "# Define predictor wrapper class\n",
    "def predict_wrapper(endpoint, session):\n",
    "    return sage.RealTimePredictor(endpoint, session, content_type='image/jpeg')\n",
    "\n",
    "# Create a deployable model\n",
    "model = ModelPackage(role=role,\n",
    "                                      model_package_arn = modelpackage_arn,\n",
    "                                      sagemaker_session = sess,\n",
    "                                      predictor_cls = predict_wrapper)\n",
    "# ARN\n",
    "print(modelpackage_arn)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Live Inference Endpoint\n",
    "\n",
    "Now we demonstrate the creation of an endpoint for live inference"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "-----------!"
     ]
    }
   ],
   "source": [
    "# Deploy the model\n",
    "predictor = model.deploy(1, 'ml.m5.xlarge', endpoint_name='barcode-endpoint')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Batch Transform Job\n",
    "\n",
    "Now let's use the model built to run a batch inference job and verify it works."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Batch Transform Input Preparation\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "sagemaker-us-east-1-635521884144\n",
      "Transform Data Location s3://sagemaker-us-east-1-635521884144/barcode/validation\n"
     ]
    }
   ],
   "source": [
    "bucket = sess.default_bucket()\n",
    "print(bucket)\n",
    "\n",
    "transform_input_prefix = \"barcode/validation\"\n",
    "TRANSFORM_WORKDIR = \"data/transform\" \n",
    "# upload data from local directory to bucket\n",
    "\n",
    "transform_input = sess.upload_data(TRANSFORM_WORKDIR, key_prefix=transform_input_prefix) \n",
    "\n",
    "print (\"Transform Data Location \" + transform_input)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Run Batch Transform\n",
    "\n",
    "Now that our batch transform input is setup, we run the transformation job next"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Using already existing model: bar-qr-code-reader-1571413449-a35a47dda-2020-04-14-12-41-18-288\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "....................\u001b[34mStarting the inference server with 48 workers.\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:10 +0000] [11] [INFO] Starting gunicorn 19.9.0\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:10 +0000] [11] [INFO] Listening at: unix:/tmp/gunicorn.sock (11)\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:10 +0000] [11] [INFO] Using worker: gevent\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:10 +0000] [15] [INFO] Booting worker with pid: 15\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:10 +0000] [16] [INFO] Booting worker with pid: 16\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:10 +0000] [64] [INFO] Booting worker with pid: 64\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:10 +0000] [65] [INFO] Booting worker with pid: 65\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:10 +0000] [113] [INFO] Booting worker with pid: 113\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:10 +0000] [114] [INFO] Booting worker with pid: 114\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:10 +0000] [178] [INFO] Booting worker with pid: 178\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:10 +0000] [210] [INFO] Booting worker with pid: 210\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:10 +0000] [259] [INFO] Booting worker with pid: 259\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:10 +0000] [308] [INFO] Booting worker with pid: 308\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:10 +0000] [309] [INFO] Booting worker with pid: 309\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:10 +0000] [405] [INFO] Booting worker with pid: 405\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:10 +0000] [453] [INFO] Booting worker with pid: 453\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:10 +0000] [455] [INFO] Booting worker with pid: 455\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:11 +0000] [456] [INFO] Booting worker with pid: 456\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:11 +0000] [557] [INFO] Booting worker with pid: 557\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:11 +0000] [588] [INFO] Booting worker with pid: 588\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:11 +0000] [653] [INFO] Booting worker with pid: 653\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:11 +0000] [705] [INFO] Booting worker with pid: 705\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:11 +0000] [704] [INFO] Booting worker with pid: 704\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:11 +0000] [754] [INFO] Booting worker with pid: 754\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:11 +0000] [755] [INFO] Booting worker with pid: 755\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:11 +0000] [757] [INFO] Booting worker with pid: 757\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:11 +0000] [806] [INFO] Booting worker with pid: 806\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:11 +0000] [942] [INFO] Booting worker with pid: 942\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:11 +0000] [1044] [INFO] Booting worker with pid: 1044\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:11 +0000] [1186] [INFO] Booting worker with pid: 1186\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:11 +0000] [1187] [INFO] Booting worker with pid: 1187\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:11 +0000] [1192] [INFO] Booting worker with pid: 1192\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:11 +0000] [1196] [INFO] Booting worker with pid: 1196\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:11 +0000] [1342] [INFO] Booting worker with pid: 1342\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:11 +0000] [1343] [INFO] Booting worker with pid: 1343\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:11 +0000] [1379] [INFO] Booting worker with pid: 1379\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:11 +0000] [1493] [INFO] Booting worker with pid: 1493\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:11 +0000] [1495] [INFO] Booting worker with pid: 1495\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:11 +0000] [1545] [INFO] Booting worker with pid: 1545\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:11 +0000] [1549] [INFO] Booting worker with pid: 1549\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:12 +0000] [1647] [INFO] Booting worker with pid: 1647\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:12 +0000] [1649] [INFO] Booting worker with pid: 1649\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:12 +0000] [1804] [INFO] Booting worker with pid: 1804\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:12 +0000] [1896] [INFO] Booting worker with pid: 1896\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:12 +0000] [1950] [INFO] Booting worker with pid: 1950\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:12 +0000] [2000] [INFO] Booting worker with pid: 2000\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:12 +0000] [2051] [INFO] Booting worker with pid: 2051\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:12 +0000] [2052] [INFO] Booting worker with pid: 2052\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:12 +0000] [2054] [INFO] Booting worker with pid: 2054\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:12 +0000] [2056] [INFO] Booting worker with pid: 2056\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:12 +0000] [2154] [INFO] Booting worker with pid: 2154\u001b[0m\n",
      "\u001b[34m169.254.255.130 - - [14/Apr/2020:12:50:41 +0000] \"GET /ping HTTP/1.1\" 200 1 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[34m169.254.255.130 - - [14/Apr/2020:12:50:41 +0000] \"GET /execution-parameters HTTP/1.1\" 404 2 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[34mStep 1\u001b[0m\n",
      "\u001b[34mStep 2\u001b[0m\n",
      "\u001b[34mStep3\u001b[0m\n",
      "\u001b[34mEndpoint invoked\u001b[0m\n",
      "\u001b[34mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:43,386] ERROR in app: Exception on /invocations [POST]\u001b[0m\n",
      "\u001b[34mTraceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/opt/program/predictor.py\", line 99, in transformation\n",
      "    barcodeInfo = ScoringService.predict(image)\n",
      "  File \"/opt/program/predictor.py\", line 56, in predict\n",
      "    print(codedict)\u001b[0m\n",
      "\u001b[34mUnboundLocalError: local variable 'codedict' referenced before assignment\u001b[0m\n",
      "\u001b[34m169.254.255.130 - - [14/Apr/2020:12:50:43 +0000] \"POST /invocations HTTP/1.1\" 500 290 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[34mStep 1\u001b[0m\n",
      "\u001b[34mStep 2\u001b[0m\n",
      "\u001b[34mStep3\u001b[0m\n",
      "\u001b[34mEndpoint invoked\u001b[0m\n",
      "\u001b[34mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:44,723] ERROR in app: Exception on /invocations [POST]\u001b[0m\n",
      "\u001b[34mTraceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/opt/program/predictor.py\", line 99, in transformation\n",
      "    barcodeInfo = ScoringService.predict(image)\n",
      "  File \"/opt/program/predictor.py\", line 56, in predict\n",
      "    print(codedict)\u001b[0m\n",
      "\u001b[34mUnboundLocalError: local variable 'codedict' referenced before assignment\u001b[0m\n",
      "\u001b[34m169.254.255.130 - - [14/Apr/2020:12:50:44 +0000] \"POST /invocations HTTP/1.1\" 500 290 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[34mStep 1\u001b[0m\n",
      "\u001b[34mStep 2\u001b[0m\n",
      "\u001b[34mStep3\u001b[0m\n",
      "\u001b[34mEndpoint invoked\u001b[0m\n",
      "\u001b[34mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:46,173] ERROR in app: Exception on /invocations [POST]\u001b[0m\n",
      "\u001b[34mTraceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/opt/program/predictor.py\", line 99, in transformation\n",
      "    barcodeInfo = ScoringService.predict(image)\n",
      "  File \"/opt/program/predictor.py\", line 56, in predict\n",
      "    print(codedict)\u001b[0m\n",
      "\u001b[34mUnboundLocalError: local variable 'codedict' referenced before assignment\u001b[0m\n",
      "\u001b[34m169.254.255.130 - - [14/Apr/2020:12:50:46 +0000] \"POST /invocations HTTP/1.1\" 500 290 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[34mStep 1\u001b[0m\n",
      "\u001b[34mStep 2\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:41.750:[sagemaker logs]: MaxConcurrentTransforms=1, MaxPayloadInMB=6, BatchStrategy=MULTI_RECORD\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:43.393:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150642.jpg: Bad HTTP status received from algorithm: 500\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:43.393:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150642.jpg: \u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:43.393:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150642.jpg: Message:\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:43.393:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150642.jpg: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:43.393:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150642.jpg: <title>500 Internal Server Error</title>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:43.393:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150642.jpg: <h1>Internal Server Error</h1>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:43.393:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150642.jpg: <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:44.727:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150850.jpg: Bad HTTP status received from algorithm: 500\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:44.727:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150850.jpg: \u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:44.727:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150850.jpg: Message:\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:44.727:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150850.jpg: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:44.727:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150850.jpg: <title>500 Internal Server Error</title>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:44.727:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150850.jpg: <h1>Internal Server Error</h1>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:44.727:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150850.jpg: <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:46.176:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150646.jpg: Bad HTTP status received from algorithm: 500\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:46.176:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150646.jpg: \u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:46.176:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150646.jpg: Message:\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:46.176:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150646.jpg: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:46.176:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150646.jpg: <title>500 Internal Server Error</title>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:46.176:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150646.jpg: <h1>Internal Server Error</h1>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:46.176:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150646.jpg: <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\u001b[0m\n",
      "\u001b[34mStep3\u001b[0m\n",
      "\u001b[34mEndpoint invoked\u001b[0m\n",
      "\u001b[35mStep3\u001b[0m\n",
      "\u001b[35mEndpoint invoked\u001b[0m\n",
      "\u001b[34mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[34m{'N35E-ZCOO-C1VL-9TL5': 'QRCODE'}\u001b[0m\n",
      "\u001b[34m169.254.255.130 - - [14/Apr/2020:12:50:47 +0000] \"POST /invocations HTTP/1.1\" 200 33 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[34mStep 1\u001b[0m\n",
      "\u001b[34mStep 2\u001b[0m\n",
      "\u001b[34mStep3\u001b[0m\n",
      "\u001b[34mEndpoint invoked\u001b[0m\n",
      "\u001b[35mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[35m{'N35E-ZCOO-C1VL-9TL5': 'QRCODE'}\u001b[0m\n",
      "\u001b[35m169.254.255.130 - - [14/Apr/2020:12:50:47 +0000] \"POST /invocations HTTP/1.1\" 200 33 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[35mStep 1\u001b[0m\n",
      "\u001b[35mStep 2\u001b[0m\n",
      "\u001b[35mStep3\u001b[0m\n",
      "\u001b[35mEndpoint invoked\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:49.154:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151143.jpg: Bad HTTP status received from algorithm: 500\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:49.154:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151143.jpg: \u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:49.154:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151143.jpg: Message:\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:49.154:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151143.jpg: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:49.154:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151143.jpg: <title>500 Internal Server Error</title>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:49.154:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151143.jpg: <h1>Internal Server Error</h1>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:49.154:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151143.jpg: <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\u001b[0m\n",
      "\u001b[34mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:49,150] ERROR in app: Exception on /invocations [POST]\u001b[0m\n",
      "\u001b[34mTraceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/opt/program/predictor.py\", line 99, in transformation\n",
      "    barcodeInfo = ScoringService.predict(image)\n",
      "  File \"/opt/program/predictor.py\", line 56, in predict\n",
      "    print(codedict)\u001b[0m\n",
      "\u001b[34mUnboundLocalError: local variable 'codedict' referenced before assignment\u001b[0m\n",
      "\u001b[34m169.254.255.130 - - [14/Apr/2020:12:50:49 +0000] \"POST /invocations HTTP/1.1\" 500 290 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[34mStep 1\u001b[0m\n",
      "\u001b[34mStep 2\u001b[0m\n",
      "\u001b[35mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[35m[2020-04-14 12:50:49,150] ERROR in app: Exception on /invocations [POST]\u001b[0m\n",
      "\u001b[35mTraceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/opt/program/predictor.py\", line 99, in transformation\n",
      "    barcodeInfo = ScoringService.predict(image)\n",
      "  File \"/opt/program/predictor.py\", line 56, in predict\n",
      "    print(codedict)\u001b[0m\n",
      "\u001b[35mUnboundLocalError: local variable 'codedict' referenced before assignment\u001b[0m\n",
      "\u001b[35m169.254.255.130 - - [14/Apr/2020:12:50:49 +0000] \"POST /invocations HTTP/1.1\" 500 290 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[35mStep 1\u001b[0m\n",
      "\u001b[35mStep 2\u001b[0m\n",
      "\u001b[34mStep3\u001b[0m\n",
      "\u001b[34mEndpoint invoked\u001b[0m\n",
      "\u001b[35mStep3\u001b[0m\n",
      "\u001b[35mEndpoint invoked\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:50.512:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150919.jpg: Bad HTTP status received from algorithm: 500\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:50.512:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150919.jpg: \u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:50.512:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150919.jpg: Message:\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:50.512:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150919.jpg: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:50.512:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150919.jpg: <title>500 Internal Server Error</title>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:50.512:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150919.jpg: <h1>Internal Server Error</h1>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:50.512:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150919.jpg: <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\u001b[0m\n",
      "\u001b[34mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:50,509] ERROR in app: Exception on /invocations [POST]\u001b[0m\n",
      "\u001b[35mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[35m[2020-04-14 12:50:50,509] ERROR in app: Exception on /invocations [POST]\u001b[0m\n",
      "\u001b[34mTraceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/opt/program/predictor.py\", line 99, in transformation\n",
      "    barcodeInfo = ScoringService.predict(image)\n",
      "  File \"/opt/program/predictor.py\", line 56, in predict\n",
      "    print(codedict)\u001b[0m\n",
      "\u001b[34mUnboundLocalError: local variable 'codedict' referenced before assignment\u001b[0m\n",
      "\u001b[34m169.254.255.130 - - [14/Apr/2020:12:50:50 +0000] \"POST /invocations HTTP/1.1\" 500 290 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[34mStep 1\u001b[0m\n",
      "\u001b[34mStep 2\u001b[0m\n",
      "\u001b[34mStep3\u001b[0m\n",
      "\u001b[34mEndpoint invoked\u001b[0m\n",
      "\u001b[35mTraceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/opt/program/predictor.py\", line 99, in transformation\n",
      "    barcodeInfo = ScoringService.predict(image)\n",
      "  File \"/opt/program/predictor.py\", line 56, in predict\n",
      "    print(codedict)\u001b[0m\n",
      "\u001b[35mUnboundLocalError: local variable 'codedict' referenced before assignment\u001b[0m\n",
      "\u001b[35m169.254.255.130 - - [14/Apr/2020:12:50:50 +0000] \"POST /invocations HTTP/1.1\" 500 290 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[35mStep 1\u001b[0m\n",
      "\u001b[35mStep 2\u001b[0m\n",
      "\u001b[35mStep3\u001b[0m\n",
      "\u001b[35mEndpoint invoked\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:52.175:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150653.jpg: Bad HTTP status received from algorithm: 500\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:52.175:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150653.jpg: \u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:52.175:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150653.jpg: Message:\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:52.175:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150653.jpg: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:52.175:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150653.jpg: <title>500 Internal Server Error</title>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:52.175:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150653.jpg: <h1>Internal Server Error</h1>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:52.175:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410150653.jpg: <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\u001b[0m\n",
      "\u001b[34mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:52,172] ERROR in app: Exception on /invocations [POST]\u001b[0m\n",
      "\u001b[34mTraceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/opt/program/predictor.py\", line 99, in transformation\n",
      "    barcodeInfo = ScoringService.predict(image)\n",
      "  File \"/opt/program/predictor.py\", line 56, in predict\n",
      "    print(codedict)\u001b[0m\n",
      "\u001b[34mUnboundLocalError: local variable 'codedict' referenced before assignment\u001b[0m\n",
      "\u001b[34m169.254.255.130 - - [14/Apr/2020:12:50:52 +0000] \"POST /invocations HTTP/1.1\" 500 290 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[34mStep 1\u001b[0m\n",
      "\u001b[34mStep 2\u001b[0m\n",
      "\u001b[35mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[35m[2020-04-14 12:50:52,172] ERROR in app: Exception on /invocations [POST]\u001b[0m\n",
      "\u001b[35mTraceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/opt/program/predictor.py\", line 99, in transformation\n",
      "    barcodeInfo = ScoringService.predict(image)\n",
      "  File \"/opt/program/predictor.py\", line 56, in predict\n",
      "    print(codedict)\u001b[0m\n",
      "\u001b[35mUnboundLocalError: local variable 'codedict' referenced before assignment\u001b[0m\n",
      "\u001b[35m169.254.255.130 - - [14/Apr/2020:12:50:52 +0000] \"POST /invocations HTTP/1.1\" 500 290 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[35mStep 1\u001b[0m\n",
      "\u001b[35mStep 2\u001b[0m\n",
      "\u001b[34mStep3\u001b[0m\n",
      "\u001b[35mStep3\u001b[0m\n",
      "\u001b[34mEndpoint invoked\u001b[0m\n",
      "\u001b[35mEndpoint invoked\u001b[0m\n",
      "\u001b[34mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[34m{'CW7L-R0WW-JF2K-KD2D': 'QRCODE'}\u001b[0m\n",
      "\u001b[34m169.254.255.130 - - [14/Apr/2020:12:50:53 +0000] \"POST /invocations HTTP/1.1\" 200 33 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[34mStep 1\u001b[0m\n",
      "\u001b[34mStep 2\u001b[0m\n",
      "\u001b[34mStep3\u001b[0m\n",
      "\u001b[34mEndpoint invoked\u001b[0m\n",
      "\u001b[35mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[35m{'CW7L-R0WW-JF2K-KD2D': 'QRCODE'}\u001b[0m\n",
      "\u001b[35m169.254.255.130 - - [14/Apr/2020:12:50:53 +0000] \"POST /invocations HTTP/1.1\" 200 33 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[35mStep 1\u001b[0m\n",
      "\u001b[35mStep 2\u001b[0m\n",
      "\u001b[35mStep3\u001b[0m\n",
      "\u001b[35mEndpoint invoked\u001b[0m\n",
      "\u001b[34mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[34m{'J2HY-S0O2-G2HV-8T9D': 'QRCODE'}\u001b[0m\n",
      "\u001b[34m169.254.255.130 - - [14/Apr/2020:12:50:55 +0000] \"POST /invocations HTTP/1.1\" 200 33 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[34mStep 1\u001b[0m\n",
      "\u001b[34mStep 2\u001b[0m\n",
      "\u001b[34mStep3\u001b[0m\n",
      "\u001b[34mEndpoint invoked\u001b[0m\n",
      "\u001b[35mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[35m{'J2HY-S0O2-G2HV-8T9D': 'QRCODE'}\u001b[0m\n",
      "\u001b[35m169.254.255.130 - - [14/Apr/2020:12:50:55 +0000] \"POST /invocations HTTP/1.1\" 200 33 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[35mStep 1\u001b[0m\n",
      "\u001b[35mStep 2\u001b[0m\n",
      "\u001b[35mStep3\u001b[0m\n",
      "\u001b[35mEndpoint invoked\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:56.381:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151126.jpg: Bad HTTP status received from algorithm: 500\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:56.381:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151126.jpg: \u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:56.381:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151126.jpg: Message:\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:56.381:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151126.jpg: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:56.381:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151126.jpg: <title>500 Internal Server Error</title>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:56.381:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151126.jpg: <h1>Internal Server Error</h1>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:56.381:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151126.jpg: <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\u001b[0m\n",
      "\u001b[34mStep3\u001b[0m\n",
      "\u001b[34mEndpoint invoked\u001b[0m\n",
      "\u001b[35mStep3\u001b[0m\n",
      "\u001b[35mEndpoint invoked\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:57.811:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151846.jpg: Bad HTTP status received from algorithm: 500\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:57.811:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151846.jpg: \u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:57.811:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151846.jpg: Message:\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:57.811:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151846.jpg: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:57.811:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151846.jpg: <title>500 Internal Server Error</title>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:57.811:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151846.jpg: <h1>Internal Server Error</h1>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:57.811:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151846.jpg: <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\u001b[0m\n",
      "\u001b[34mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:57,807] ERROR in app: Exception on /invocations [POST]\u001b[0m\n",
      "\u001b[35mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[35m[2020-04-14 12:50:57,807] ERROR in app: Exception on /invocations [POST]\u001b[0m\n",
      "\u001b[34mTraceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/opt/program/predictor.py\", line 99, in transformation\n",
      "    barcodeInfo = ScoringService.predict(image)\n",
      "  File \"/opt/program/predictor.py\", line 56, in predict\n",
      "    print(codedict)\u001b[0m\n",
      "\u001b[34mUnboundLocalError: local variable 'codedict' referenced before assignment\u001b[0m\n",
      "\u001b[34m169.254.255.130 - - [14/Apr/2020:12:50:57 +0000] \"POST /invocations HTTP/1.1\" 500 290 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[34mStep 1\u001b[0m\n",
      "\u001b[34mStep 2\u001b[0m\n",
      "\u001b[34mStep3\u001b[0m\n",
      "\u001b[34mEndpoint invoked\u001b[0m\n",
      "\u001b[35mTraceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/opt/program/predictor.py\", line 99, in transformation\n",
      "    barcodeInfo = ScoringService.predict(image)\n",
      "  File \"/opt/program/predictor.py\", line 56, in predict\n",
      "    print(codedict)\u001b[0m\n",
      "\u001b[35mUnboundLocalError: local variable 'codedict' referenced before assignment\u001b[0m\n",
      "\u001b[35m169.254.255.130 - - [14/Apr/2020:12:50:57 +0000] \"POST /invocations HTTP/1.1\" 500 290 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[35mStep 1\u001b[0m\n",
      "\u001b[35mStep 2\u001b[0m\n",
      "\u001b[35mStep3\u001b[0m\n",
      "\u001b[35mEndpoint invoked\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:59.244:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151848.jpg: Bad HTTP status received from algorithm: 500\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:59.244:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151848.jpg: \u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:59.244:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151848.jpg: Message:\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:59.244:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151848.jpg: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:59.244:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151848.jpg: <title>500 Internal Server Error</title>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:59.244:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151848.jpg: <h1>Internal Server Error</h1>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:50:59.244:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151848.jpg: <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\u001b[0m\n",
      "\u001b[34mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:50:59,241] ERROR in app: Exception on /invocations [POST]\u001b[0m\n",
      "\u001b[34mTraceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/opt/program/predictor.py\", line 99, in transformation\n",
      "    barcodeInfo = ScoringService.predict(image)\n",
      "  File \"/opt/program/predictor.py\", line 56, in predict\n",
      "    print(codedict)\u001b[0m\n",
      "\u001b[34mUnboundLocalError: local variable 'codedict' referenced before assignment\u001b[0m\n",
      "\u001b[34m169.254.255.130 - - [14/Apr/2020:12:50:59 +0000] \"POST /invocations HTTP/1.1\" 500 290 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[34mStep 1\u001b[0m\n",
      "\u001b[34mStep 2\u001b[0m\n",
      "\u001b[35mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[35m[2020-04-14 12:50:59,241] ERROR in app: Exception on /invocations [POST]\u001b[0m\n",
      "\u001b[35mTraceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/opt/program/predictor.py\", line 99, in transformation\n",
      "    barcodeInfo = ScoringService.predict(image)\n",
      "  File \"/opt/program/predictor.py\", line 56, in predict\n",
      "    print(codedict)\u001b[0m\n",
      "\u001b[35mUnboundLocalError: local variable 'codedict' referenced before assignment\u001b[0m\n",
      "\u001b[35m169.254.255.130 - - [14/Apr/2020:12:50:59 +0000] \"POST /invocations HTTP/1.1\" 500 290 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[35mStep 1\u001b[0m\n",
      "\u001b[35mStep 2\u001b[0m\n",
      "\u001b[34mStep3\u001b[0m\n",
      "\u001b[34mEndpoint invoked\u001b[0m\n",
      "\u001b[35mStep3\u001b[0m\n",
      "\u001b[35mEndpoint invoked\u001b[0m\n",
      "\u001b[34mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[34m{'CW7L-R0WW-JF2K-KD2D': 'QRCODE', 'N35E-ZCOO-C1VL-9TL5': 'QRCODE'}\u001b[0m\n",
      "\u001b[34m169.254.255.130 - - [14/Apr/2020:12:51:00 +0000] \"POST /invocations HTTP/1.1\" 200 66 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[34mStep 1\u001b[0m\n",
      "\u001b[34mStep 2\u001b[0m\n",
      "\u001b[34mStep3\u001b[0m\n",
      "\u001b[34mEndpoint invoked\u001b[0m\n",
      "\u001b[35mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[35m{'CW7L-R0WW-JF2K-KD2D': 'QRCODE', 'N35E-ZCOO-C1VL-9TL5': 'QRCODE'}\u001b[0m\n",
      "\u001b[35m169.254.255.130 - - [14/Apr/2020:12:51:00 +0000] \"POST /invocations HTTP/1.1\" 200 66 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[35mStep 1\u001b[0m\n",
      "\u001b[35mStep 2\u001b[0m\n",
      "\u001b[35mStep3\u001b[0m\n",
      "\u001b[35mEndpoint invoked\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:02.417:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151929.jpg: Bad HTTP status received from algorithm: 500\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:02.417:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151929.jpg: \u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:02.417:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151929.jpg: Message:\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:02.417:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151929.jpg: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:02.417:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151929.jpg: <title>500 Internal Server Error</title>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:02.417:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151929.jpg: <h1>Internal Server Error</h1>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:02.417:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151929.jpg: <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\u001b[0m\n",
      "\u001b[34mStep3\u001b[0m\n",
      "\u001b[34mEndpoint invoked\u001b[0m\n",
      "\u001b[35mStep3\u001b[0m\n",
      "\u001b[35mEndpoint invoked\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:04.007:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410152331.jpg: Bad HTTP status received from algorithm: 500\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:04.007:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410152331.jpg: \u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:04.007:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410152331.jpg: Message:\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:04.007:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410152331.jpg: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:04.007:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410152331.jpg: <title>500 Internal Server Error</title>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:04.007:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410152331.jpg: <h1>Internal Server Error</h1>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:04.007:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410152331.jpg: <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\u001b[0m\n",
      "\u001b[34mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:51:04,004] ERROR in app: Exception on /invocations [POST]\u001b[0m\n",
      "\u001b[34mTraceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/opt/program/predictor.py\", line 99, in transformation\n",
      "    barcodeInfo = ScoringService.predict(image)\n",
      "  File \"/opt/program/predictor.py\", line 56, in predict\n",
      "    print(codedict)\u001b[0m\n",
      "\u001b[34mUnboundLocalError: local variable 'codedict' referenced before assignment\u001b[0m\n",
      "\u001b[34m169.254.255.130 - - [14/Apr/2020:12:51:04 +0000] \"POST /invocations HTTP/1.1\" 500 290 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[34mStep 1\u001b[0m\n",
      "\u001b[34mStep 2\u001b[0m\n",
      "\u001b[34mStep3\u001b[0m\n",
      "\u001b[34mEndpoint invoked\u001b[0m\n",
      "\u001b[35mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[35m[2020-04-14 12:51:04,004] ERROR in app: Exception on /invocations [POST]\u001b[0m\n",
      "\u001b[35mTraceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/opt/program/predictor.py\", line 99, in transformation\n",
      "    barcodeInfo = ScoringService.predict(image)\n",
      "  File \"/opt/program/predictor.py\", line 56, in predict\n",
      "    print(codedict)\u001b[0m\n",
      "\u001b[35mUnboundLocalError: local variable 'codedict' referenced before assignment\u001b[0m\n",
      "\u001b[35m169.254.255.130 - - [14/Apr/2020:12:51:04 +0000] \"POST /invocations HTTP/1.1\" 500 290 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[35mStep 1\u001b[0m\n",
      "\u001b[35mStep 2\u001b[0m\n",
      "\u001b[35mStep3\u001b[0m\n",
      "\u001b[35mEndpoint invoked\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:05.560:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151850.jpg: Bad HTTP status received from algorithm: 500\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:05.560:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151850.jpg: \u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:05.560:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151850.jpg: Message:\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:05.560:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151850.jpg: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:05.560:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151850.jpg: <title>500 Internal Server Error</title>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:05.560:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151850.jpg: <h1>Internal Server Error</h1>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:05.560:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410151850.jpg: <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\u001b[0m\n",
      "\u001b[34mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:51:05,556] ERROR in app: Exception on /invocations [POST]\u001b[0m\n",
      "\u001b[34mTraceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/opt/program/predictor.py\", line 99, in transformation\n",
      "    barcodeInfo = ScoringService.predict(image)\n",
      "  File \"/opt/program/predictor.py\", line 56, in predict\n",
      "    print(codedict)\u001b[0m\n",
      "\u001b[34mUnboundLocalError: local variable 'codedict' referenced before assignment\u001b[0m\n",
      "\u001b[34m169.254.255.130 - - [14/Apr/2020:12:51:05 +0000] \"POST /invocations HTTP/1.1\" 500 290 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[34mStep 1\u001b[0m\n",
      "\u001b[34mStep 2\u001b[0m\n",
      "\u001b[34mStep3\u001b[0m\n",
      "\u001b[34mEndpoint invoked\u001b[0m\n",
      "\u001b[35mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[35m[2020-04-14 12:51:05,556] ERROR in app: Exception on /invocations [POST]\u001b[0m\n",
      "\u001b[35mTraceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/opt/program/predictor.py\", line 99, in transformation\n",
      "    barcodeInfo = ScoringService.predict(image)\n",
      "  File \"/opt/program/predictor.py\", line 56, in predict\n",
      "    print(codedict)\u001b[0m\n",
      "\u001b[35mUnboundLocalError: local variable 'codedict' referenced before assignment\u001b[0m\n",
      "\u001b[35m169.254.255.130 - - [14/Apr/2020:12:51:05 +0000] \"POST /invocations HTTP/1.1\" 500 290 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[35mStep 1\u001b[0m\n",
      "\u001b[35mStep 2\u001b[0m\n",
      "\u001b[35mStep3\u001b[0m\n",
      "\u001b[35mEndpoint invoked\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:06.789:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410152405.jpg: Bad HTTP status received from algorithm: 500\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:06.789:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410152405.jpg: \u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:06.789:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410152405.jpg: Message:\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:06.789:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410152405.jpg: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:06.789:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410152405.jpg: <title>500 Internal Server Error</title>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:06.789:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410152405.jpg: <h1>Internal Server Error</h1>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:06.789:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410152405.jpg: <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\u001b[0m\n",
      "\u001b[34mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:51:06,786] ERROR in app: Exception on /invocations [POST]\u001b[0m\n",
      "\u001b[34mTraceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/opt/program/predictor.py\", line 99, in transformation\n",
      "    barcodeInfo = ScoringService.predict(image)\n",
      "  File \"/opt/program/predictor.py\", line 56, in predict\n",
      "    print(codedict)\u001b[0m\n",
      "\u001b[34mUnboundLocalError: local variable 'codedict' referenced before assignment\u001b[0m\n",
      "\u001b[34m169.254.255.130 - - [14/Apr/2020:12:51:06 +0000] \"POST /invocations HTTP/1.1\" 500 290 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[34mStep 1\u001b[0m\n",
      "\u001b[34mStep 2\u001b[0m\n",
      "\u001b[34mStep3\u001b[0m\n",
      "\u001b[34mEndpoint invoked\u001b[0m\n",
      "\u001b[35mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[35m[2020-04-14 12:51:06,786] ERROR in app: Exception on /invocations [POST]\u001b[0m\n",
      "\u001b[35mTraceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/opt/program/predictor.py\", line 99, in transformation\n",
      "    barcodeInfo = ScoringService.predict(image)\n",
      "  File \"/opt/program/predictor.py\", line 56, in predict\n",
      "    print(codedict)\u001b[0m\n",
      "\u001b[35mUnboundLocalError: local variable 'codedict' referenced before assignment\u001b[0m\n",
      "\u001b[35m169.254.255.130 - - [14/Apr/2020:12:51:06 +0000] \"POST /invocations HTTP/1.1\" 500 290 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[35mStep 1\u001b[0m\n",
      "\u001b[35mStep 2\u001b[0m\n",
      "\u001b[35mStep3\u001b[0m\n",
      "\u001b[35mEndpoint invoked\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:07.988:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410152942.jpg: Bad HTTP status received from algorithm: 500\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:07.988:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410152942.jpg: \u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:07.988:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410152942.jpg: Message:\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:07.989:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410152942.jpg: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:07.989:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410152942.jpg: <title>500 Internal Server Error</title>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:07.989:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410152942.jpg: <h1>Internal Server Error</h1>\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:07.989:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410152942.jpg: <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\u001b[0m\n",
      "\u001b[34mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[34m[2020-04-14 12:51:07,985] ERROR in app: Exception on /invocations [POST]\u001b[0m\n",
      "\u001b[35mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[35m[2020-04-14 12:51:07,985] ERROR in app: Exception on /invocations [POST]\u001b[0m\n",
      "\u001b[34mTraceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/opt/program/predictor.py\", line 99, in transformation\n",
      "    barcodeInfo = ScoringService.predict(image)\n",
      "  File \"/opt/program/predictor.py\", line 56, in predict\n",
      "    print(codedict)\u001b[0m\n",
      "\u001b[34mUnboundLocalError: local variable 'codedict' referenced before assignment\u001b[0m\n",
      "\u001b[34m169.254.255.130 - - [14/Apr/2020:12:51:07 +0000] \"POST /invocations HTTP/1.1\" 500 290 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[34mStep 1\u001b[0m\n",
      "\u001b[34mStep 2\u001b[0m\n",
      "\u001b[34mStep3\u001b[0m\n",
      "\u001b[34mEndpoint invoked\u001b[0m\n",
      "\u001b[35mTraceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 2446, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1951, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1820, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1949, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/usr/local/lib/python3.6/dist-packages/flask/app.py\", line 1935, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"/opt/program/predictor.py\", line 99, in transformation\n",
      "    barcodeInfo = ScoringService.predict(image)\n",
      "  File \"/opt/program/predictor.py\", line 56, in predict\n",
      "    print(codedict)\u001b[0m\n",
      "\u001b[35mUnboundLocalError: local variable 'codedict' referenced before assignment\u001b[0m\n",
      "\u001b[35m169.254.255.130 - - [14/Apr/2020:12:51:07 +0000] \"POST /invocations HTTP/1.1\" 500 290 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[35mStep 1\u001b[0m\n",
      "\u001b[35mStep 2\u001b[0m\n",
      "\u001b[35mStep3\u001b[0m\n",
      "\u001b[35mEndpoint invoked\u001b[0m\n",
      "\u001b[34mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[34m{'N35E-ZCOO-C1VL-9TL5': 'QRCODE', 'CW7L-R0WW-JF2K-KD2D': 'QRCODE', '2888-ABFS-N1IM-D6R0': 'QRCODE', '9UIQ-NVR1-DD58-KCYY': 'QRCODE', 'J2HY-S0O2-G2HV-8T9D': 'QRCODE'}\u001b[0m\n",
      "\u001b[34m169.254.255.130 - - [14/Apr/2020:12:51:09 +0000] \"POST /invocations HTTP/1.1\" 200 165 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[34mStep 1\u001b[0m\n",
      "\u001b[34mStep 2\u001b[0m\n",
      "\u001b[34mStep3\u001b[0m\n",
      "\u001b[34mEndpoint invoked\u001b[0m\n",
      "\u001b[35mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[35m{'N35E-ZCOO-C1VL-9TL5': 'QRCODE', 'CW7L-R0WW-JF2K-KD2D': 'QRCODE', '2888-ABFS-N1IM-D6R0': 'QRCODE', '9UIQ-NVR1-DD58-KCYY': 'QRCODE', 'J2HY-S0O2-G2HV-8T9D': 'QRCODE'}\u001b[0m\n",
      "\u001b[35m169.254.255.130 - - [14/Apr/2020:12:51:09 +0000] \"POST /invocations HTTP/1.1\" 200 165 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[35mStep 1\u001b[0m\n",
      "\u001b[35mStep 2\u001b[0m\n",
      "\u001b[35mStep3\u001b[0m\n",
      "\u001b[35mEndpoint invoked\u001b[0m\n",
      "\u001b[32m2020-04-14T12:51:10.980:[sagemaker logs]: sagemaker-us-east-1-635521884144/barcode/validation/IMG20200410153214.jpg: Too much data for max payload size\u001b[0m\n",
      "\u001b[34mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[34m{'N35E-ZCOO-C1VL-9TL5': 'QRCODE', 'CW7L-R0WW-JF2K-KD2D': 'QRCODE'}\u001b[0m\n",
      "\u001b[34m169.254.255.130 - - [14/Apr/2020:12:51:10 +0000] \"POST /invocations HTTP/1.1\" 200 66 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\u001b[35mBarcode Data and Barcode Type: \n",
      "\u001b[0m\n",
      "\u001b[35m{'N35E-ZCOO-C1VL-9TL5': 'QRCODE', 'CW7L-R0WW-JF2K-KD2D': 'QRCODE'}\u001b[0m\n",
      "\u001b[35m169.254.255.130 - - [14/Apr/2020:12:51:10 +0000] \"POST /invocations HTTP/1.1\" 200 66 \"-\" \"Go-http-client/1.1\"\u001b[0m\n",
      "\n"
     ]
    },
    {
     "ename": "UnexpectedStatusException",
     "evalue": "Error for Transform job bar-qr-code-reader-1571413449-a35a47dda-2020-04-14-12-46-56-608: Failed. Reason: AlgorithmError: See job logs for more information",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mUnexpectedStatusException\u001b[0m                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-7-c1f789b45068>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      2\u001b[0m                                 output_path=\"s3://\"+bucket+\"/barcode/batch-transform-output\")\n\u001b[1;32m      3\u001b[0m \u001b[0mtransformer\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtransform\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtransform_input\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcontent_type\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'image/jpeg'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 4\u001b[0;31m \u001b[0mtransformer\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      5\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      6\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Batch Transform output saved to \"\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0mtransformer\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0moutput_path\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/transformer.py\u001b[0m in \u001b[0;36mwait\u001b[0;34m(self, logs)\u001b[0m\n\u001b[1;32m    253\u001b[0m         \u001b[0;34m\"\"\"Placeholder docstring\"\"\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    254\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_ensure_last_transform_job\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 255\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlatest_transform_job\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mlogs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mlogs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    256\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    257\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mstop_transform_job\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mwait\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/transformer.py\u001b[0m in \u001b[0;36mwait\u001b[0;34m(self, logs)\u001b[0m\n\u001b[1;32m    382\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mwait\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlogs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    383\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mlogs\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 384\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msagemaker_session\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlogs_for_transform_job\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjob_name\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mwait\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    385\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    386\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msagemaker_session\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait_for_transform_job\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjob_name\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/session.py\u001b[0m in \u001b[0;36mlogs_for_transform_job\u001b[0;34m(self, job_name, wait, poll)\u001b[0m\n\u001b[1;32m   3189\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   3190\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mwait\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 3191\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_check_job_status\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mjob_name\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdescription\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"TransformJobStatus\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   3192\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mdot\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   3193\u001b[0m                 \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/session.py\u001b[0m in \u001b[0;36m_check_job_status\u001b[0;34m(self, job, desc, status_key_name)\u001b[0m\n\u001b[1;32m   2613\u001b[0m                 ),\n\u001b[1;32m   2614\u001b[0m                 \u001b[0mallowed_statuses\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"Completed\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"Stopped\"\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 2615\u001b[0;31m                 \u001b[0mactual_status\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mstatus\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   2616\u001b[0m             )\n\u001b[1;32m   2617\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mUnexpectedStatusException\u001b[0m: Error for Transform job bar-qr-code-reader-1571413449-a35a47dda-2020-04-14-12-46-56-608: Failed. Reason: AlgorithmError: See job logs for more information"
     ]
    }
   ],
   "source": [
    "transformer = model.transformer(1, 'ml.m5.12xlarge', \n",
    "                                output_path=\"s3://\"+bucket+\"/barcode/batch-transform-output\")\n",
    "transformer.transform(transform_input, content_type='image/jpeg')\n",
    "transformer.wait()\n",
    "\n",
    "print(\"Batch Transform output saved to \" + transformer.output_path)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "IMG20200410151016.jpg.out\n",
      "{\"N35E-ZCOO-C1VL-9TL5\": \"QRCODE\"}\n",
      "IMG20200410151235.jpg.out\n",
      "{\"CW7L-R0WW-JF2K-KD2D\": \"QRCODE\"}\n",
      "IMG20200410151253.jpg.out\n",
      "{\"J2HY-S0O2-G2HV-8T9D\": \"QRCODE\"}\n",
      "IMG20200410151309.jpg.out\n",
      "{\"CW7L-R0WW-JF2K-KD2D\": \"QRCODE\", \"N35E-ZCOO-C1VL-9TL5\": \"QRCODE\"}\n",
      "IMG20200410153141.jpg.out\n",
      "{\"N35E-ZCOO-C1VL-9TL5\": \"QRCODE\", \"CW7L-R0WW-JF2K-KD2D\": \"QRCODE\", \"2888-ABFS-N1IM-D6R0\": \"QRCODE\", \"9UIQ-NVR1-DD58-KCYY\": \"QRCODE\", \"J2HY-S0O2-G2HV-8T9D\": \"QRCODE\"}\n",
      "IMG20200410153152.jpg.out\n",
      "{\"N35E-ZCOO-C1VL-9TL5\": \"QRCODE\", \"CW7L-R0WW-JF2K-KD2D\": \"QRCODE\"}\n"
     ]
    }
   ],
   "source": [
    "# Print the outputs\n",
    "\n",
    "s3 = boto3.resource('s3')\n",
    "my_bucket = s3.Bucket(sess.default_bucket())\n",
    "\n",
    "for object_summary in my_bucket.objects.filter(Prefix=\"barcode/batch-transform-output\"+ \"/\"):\n",
    "   file_name = object_summary.key.split('/')[-1]\n",
    "   print(file_name)\n",
    "   s3.Bucket(sess.default_bucket()).download_file(\"barcode/\"+\"batch-transform-output\" +\"/\"+ file_name,  'batch_results')\n",
    "   with open('batch_results') as f:\n",
    "       results = f.readlines()  \n",
    "   \n",
    "   print(\"\".join(results))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Clean Up Endpoint"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "predictor.delete_endpoint()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "conda_python3",
   "language": "python",
   "name": "conda_python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
